config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from hackupc.proposal.views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('hackupc.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here

    url(r'^proposals/', include('hackupc.proposal.urls', namespace='proposals')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

hackupc/proposal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^list/$',
        view=views.ProposalListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^add/$',
        view=views.ProposalCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^detail/(?P<pk>\d+)/$',
        view=views.ProposalDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.ProposalDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^edit/(?P<pk>\d+)/$',
        view=views.ProposalUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^vote/(?P<pk>\d+)/$',
        view=views.vote_proposal,
        name='vote'
    ),
    url(
        regex=r'^getPDFData/(?P<pk>\d+)/$',
        view=views.get_pdf_data,
        name='getPDFdata'
    ),
]

hackupc/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/validate/$',
        view=views.UserValidateProfileView.as_view(),
        name='validate'
    )
]

hackupc/proposal/models.py
from __future__ import unicode_literals

from model_utils.models import TimeStampedModel
from django.db import models
from hackupc.users.models import User
# Create your models here.


class Proposal(TimeStampedModel):
    title = models.TextField(blank=False, max_length=100)
    description = models.TextField(blank=False, max_length=2000)
    image = models.ImageField(blank=False)
    created_by = models.ForeignKey(User)

    @property
    def get_votes(self):
        return self.proposalvote_set.all().count()


class ProposalVote(TimeStampedModel):
    user = models.ForeignKey(User)
    proposal = models.ForeignKey(Proposal)

    class Meta:
        unique_together = ("user", "proposal")

hackupc/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
import requests
from base64 import b64decode
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.core.files.base import ContentFile
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.utils import timezone


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=False, max_length=255)
    surname = models.CharField(blank=False, max_length=255)

    document_id = models.CharField(max_length=50)

    is_validated = models.BooleanField(default=False)

    sign_photo = models.ImageField()

    member_since = models.IntegerField(default=timezone.now().year)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    @staticmethod
    def validations_check(validations):
        if validations['test_correspondence_visible_mrz_id_number'] != 'ok':
            return False
        if validations['test_correspondence_visible_mrz_name'] != 'ok':
            return False
        if validations['test_correspondence_visible_mrz_surname'] != 'ok':
            return False
        if validations['test_mrz_global_integrity'] != 'ok':
            return False
        if validations['test_global_authenticity_value'] != 'ok':
            return False
        aut_ratio = float(validations['test_global_authenticity_ratio'])
        if aut_ratio < 0.95:
            return False
        return True

    @staticmethod
    def is_repeated_id(document_id):
        return User.objects.filter(document_id=document_id).count() > 0

    def validate_id(self, frontal_photo, back_photo):
        signaturit_url = 'https://api.sandbox.signaturit.com/v3/photoid/validate.json'
        headers = {'Authorization': 'Bearer ' + settings.SIGNATURIT_TOKEN}
        files = {'front': frontal_photo,
                 'back': back_photo}
        r = requests.post(signaturit_url, files=files, headers=headers)
        try:
            response = r.json()

            if User.validations_check(response['validations']):
                document_id = response['data']['id_number']
                if User.is_repeated_id(document_id):
                    return "repeated"
                self.document_id = document_id
                self.name = response['data']['name'].title()
                self.surname = response['data']['surname'].title()
                signature_data = b64decode(response['signature'])
                self.sign_photo = ContentFile(signature_data, self.document_id+'.png')
                self.is_validated = True
                self.save()
                return True
        except Exception as e:
            return "not_valid"
        return "not_valid"


    @property
    def number_votes(self):
        return self.proposalvote_set.all().count()

hackupc/proposal/forms.py
from django.forms import ModelForm
from .models import Proposal


class ProposalForm(ModelForm):

    class Meta:
        model = Proposal
        fields = ('title', 'description', 'image')

hackupc/users/forms.py
from django.forms import forms, fields


class ValidateProfileForm(forms.Form):
    frontal_photo = fields.ImageField(required=True)
    back_photo = fields.ImageField(required=True)

hackupc/proposal/views.py
import base64
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import UpdateView, CreateView, DetailView, ListView, DeleteView

from hackupc.users.models import User
from .models import Proposal, ProposalVote
from .forms import ProposalForm


class ProposalCreateView(LoginRequiredMixin, CreateView):
    model = Proposal
    form_class = ProposalForm
    template_name = 'proposals/proposal_add.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('proposals:detail', kwargs={'pk': self.object.pk})


class ProposalDetailView(LoginRequiredMixin, DetailView):
    model = Proposal
    template_name = 'proposals/proposal_detail.html'


class ProposalUpdateView(LoginRequiredMixin, UpdateView):

    model = Proposal
    form_class = ProposalForm
    template_name = 'proposals/proposal_edit.html'

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('proposals:detail', kwargs={'pk': self.object.pk})


class ProposalListView(LoginRequiredMixin, ListView):
    model = Proposal
    template_name = 'proposals/proposal_list.html'

    def get_queryset(self):
        return Proposal.objects.filter(created_by=self.request.user)


class ProposalDeleteView(LoginRequiredMixin, DeleteView):
    model = Proposal

    def get_success_url(self):
        return reverse('proposals:list')


class HomeView(LoginRequiredMixin, ListView):
    model = Proposal
    template_name = 'pages/home.html'


def vote_proposal(request, pk):
    prop = Proposal.objects.get(pk=pk)
    user = User.objects.get(pk=int(request.POST['voter_id']))
    ProposalVote.objects.create(proposal=prop, user=user)
    return HttpResponse()


def get_pdf_data(request, pk):
    votes = ProposalVote.objects.filter(proposal__pk=int(pk))
    ret = {'a': []}
    for vote in votes:
        ret['a'].append({'id': vote.user.document_id,
                         'name': vote.user.name,
                         'surname': vote.user.surname,
                         'signature': 'data:image/jpeg;base64,'+base64.b64encode(vote.user.sign_photo.read())})
    return JsonResponse(ret)

hackupc/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import base64

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.defaultfilters import register
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView

from .models import User
from .forms import ValidateProfileForm
from hackupc.proposal.models import ProposalVote


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'surname']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserValidateProfileView(LoginRequiredMixin, FormView):
    form_class = ValidateProfileForm
    template_name = 'users/user_validate.html'

    def get_context_data(self, **kwargs):
        context = super(UserValidateProfileView, self).get_context_data(**kwargs)
        context['error'] = False
        if self.request.GET.get('error', 0) != 0:
            context['error'] = self.request.GET['error']
        context['user'] = User.objects.get(username=self.kwargs.get('username', None))
        return context

    def form_valid(self, form):
        result = self.request.user.validate_id(form.cleaned_data['frontal_photo'].read(),
                                               form.cleaned_data['back_photo'].read())
        if result is True:
            return HttpResponseRedirect(self.get_success_url())
        elif result == 'repeated':
            return HttpResponseRedirect(reverse('users:validate', args=[self.request.user.username])+'?error=repeated')
        return HttpResponseRedirect(reverse('users:validate', args=[self.request.user.username])+'?error=not_valid')

    def get_success_url(self):
        return self.request.user.get_absolute_url()


@register.filter(name='has_voted')
def has_voted_proposal(obj, prop_id):
    return ProposalVote.objects.filter(user=obj, proposal__pk=prop_id).count() == 1

hackupc/templates/proposals/proposal_add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add Proposal{% endblock %}

{% block content %}
    <h2>Add a new proposal</h2>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <label for="id_title" class="form-control-label  requiredField">
                    Title<span class="asteriskField">*</span> </label>
                <input class="form-control" id="id_title" maxlength="100" name="title" required="">
            </div>
            <div class="col-md-6">
                <label for="id_image" class="form-control-label  requiredField">
                    Image<span class="asteriskField">*</span> </label>
                <input class="clearablefileinput" id="id_image" name="image" type="file" required="">
            </div>

            <div class="col-md-12">
                <label for="id_description" class="form-control-label  requiredField">
                    Description<span class="asteriskField">*</span> </label>
                <textarea class="textarea form-control" cols="40" id="id_description" maxlength="2000" name="description" rows="10" required=""></textarea>
            </div>
        </div>
        <div class="row" style="margin-top: 20px">
            <div class="col-md-1 col-md-offset-11">
                <button type="submit" class="btn btn-theme03">ADD</button>
            </div>
        </div>
    </form>
{% endblock content %}

hackupc/templates/proposals/proposal_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Proposal {{ object.title }}{% endblock %}

{% block content %}
    {% if object.created_by == request.user %}
        <div class="row">
            <div class="col-md-3 col-md-offset-9 text-right">
                <button class="btn btn-theme02" onclick="generatePDF()">Generate PDF</button>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="{{ object.image.url }}">
        </div>
        <div class="col-md-6">
            <h4><b>{{ object.title }}</b></h4>
            <div class="row">
                <p class="prop-voters"><i class="fa fa-user"></i> {{ object.get_votes }} Votes</p>
                <p style="word-break: break-all ">{{ object.description }}</p>
            </div>
        </div>
    </div>
    {% if object.created_by == request.user %}
        <div class="row" style="margin-top: 20px">
            <div class="col-md-1 ">
                <a role="button" class="btn btn-theme" href="{% url 'proposals:update' object.pk %}">Edit</a>
            </div>
            <div class="col-md-1">
                <button data-toggle="modal" data-target="#myModal" class="btn btn-theme04">Delete</button>
            </div>
            {% if not request.user|has_voted:object.pk and request.user.is_validated %}
                <div class="col-md-2 col-md-offset-8">
                    <button class="btn btn-sm btn-theme03" onclick="voteProposal({{ object.pk }})">VOTE</button>
                </div>
            {% endif %}
        </div>
    {% elif not request.user|has_voted:object.pk and request.user.is_validated %}
        <div class="row">
            <div class="col-md-2">
                <button class="btn btn-sm btn-theme03" onclick="voteProposal({{ object.pk }})">VOTE</button>
            </div>
        </div>
    {% endif %}


    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Delete this Proposal</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure?</p>
                </div>
                <div class="modal-footer">
                    <form method="post" action="{% url 'proposals:delete' object.pk %}" >
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Yes</button>
                    </form>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
    {% csrf_token %}
{% endblock content %}


{% block javascript %}
    {{ block.super }}
    {% if object.created_by == request.user %}
        <script type="application/javascript">
            $('#my-proposals').addClass('active');
        </script>
    {% else %}
        <script type="application/javascript">
            $('#proposals').addClass('active');
        </script>
    {% endif %}
    <script type="application/javascript">
        var user_id = {{ request.user.pk }};
        function voteProposal(proposal_id) {
            $.ajax({
                type: "POST",
                url: '/proposals/vote/' + proposal_id + '/',
                data:{
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    voter_id : user_id
                },
                success: function () {
                    window.location.reload();
                }
            });
        };
        var proposal_pk = {{ object.pk }};
        var proposal_title = '{{ object.title }}';
        var proposal_desc = '{{ object.description }}';
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.debug.js"></script>
    <script src="{% static 'js/generatePDF.js' %}"></script>
{% endblock javascript %}

hackupc/templates/proposals/proposal_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit Proposal{% endblock %}

{% block content %}
    <h2>Edit proposal - {{ object.title }}</h2>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <label for="id_title" class="form-control-label  requiredField">
                    Title<span class="asteriskField">*</span> </label>
                <input class="form-control" id="id_title" maxlength="100" name="title" value="{{ object.title }}" required="">
            </div>
            <div class="col-md-6">
                <label for="id_image" class="form-control-label  requiredField">
                    Image<span class="asteriskField">*</span> </label>
                <br>
                Currently: <a href="{{ object.image.url }}">{{ object.image.name }}</a>
                <br>
                <input class="clearablefileinput" id="id_image" name="image" type="file" >
            </div>

            <div class="col-md-12">
                <label for="id_description" class="form-control-label  requiredField">
                    Description<span class="asteriskField">*</span> </label>
                <textarea class="textarea form-control" cols="40" id="id_description" maxlength="2000" name="description" rows="10" required="">{{ object.description }}</textarea>
            </div>
        </div>
        <div class="row" style="margin-top: 20px">
            <div class="col-md-2 col-md-offset-10">
                <button type="submit" class="btn btn-theme03">Save Changes</button>
            </div>
        </div>
    </form>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script type="application/javascript">
        $('#my-proposals').addClass('active');
    </script>
{% endblock javascript %}

hackupc/templates/proposals/proposal_list.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-2 col-md-offset-10">
            <a role="button" class="btn btn-theme03" href="{% url 'proposals:create' %}">Add a proposal</a>
        </div>
    </div>
    {% for object in object_list %}
        <div class="col-lg-4 col-md-4 col-sm-4 mb">
            <div class="content-panel pn" >
                <div class="proposal">
                    <div class="prop-bg" style="background-image: url('{{ object.image.url }}')">
                        <div class="col-xs-4 col-xs-offset-8">
                            {% if not request.user|has_voted:object.pk and request.user.is_validated %}
                            <button class="btn btn-sm btn-theme03" onclick="voteProposal({{ object.pk }})">VOTE</button>
                            {% endif %}
                        </div>
                        <div class="prop-title">
                            <h3>{{ object.title }}</h3>
                        </div>
                    </div>
                    <div class="prop-text">
                        <p>{{ object.description|truncatechars:25 }}</p>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p class="prop-voters"><i class="fa fa-user"></i> {{ object.get_votes }} Votes</p>
                        </div>
                        <div class="col-md-6 text-right">
                            <a role="button" class="btn btn-theme03" href="{% url 'proposals:detail' object.pk %}">See</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="application/javascript">
        $('#my-proposals').addClass('active');
        var user_id = {{ request.user.pk }};
        function voteProposal(proposal_id) {
            $.ajax({
                type: "POST",
                url: '/proposals/vote/' + proposal_id + '/',
                data:{
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    voter_id : user_id
                },
                success: function () {
                    window.location.reload();
                }
            });
        }
    </script>
{% endblock javascript %}